services:
  ncr_client:
    container_name: OCR_client
    restart: always
    image: ocr_client
    build: 
      context: ../client
      dockerfile: dockerfile.client
    volumes:
      - /etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ../client/dist:/usr/share/nginx/html
      - /etc/nginx/ssl/server.crt:/etc/nginx/ssl/server.crt
      - /etc/nginx/ssl/server.key:/etc/nginx/ssl/server.key
    networks:
      - nginx
    ports:
      - "8080:8080"
      - "80:80"
  ncr_api:
    container_name: OCR_api
    restart: always
    image: ocr_api
    build: 
      context: ../api
      dockerfile: dockerfile.api
    networks:
      - nginx
    ports:
      - "5000:5000"

networks:
  nginx:
    driver: bridge